version: "3.7"

services:
  wp:
    image: "wordpress:${WP_TAG}"
    ports:
      - ${WP_IP}:${WP_PORT}:80
    volumes:
      - "./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - ".:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    restart: unless-stopped

  wpcli:
    image: "wordpress:cli"
    volumes:
      - "./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini"
      - "./wp-app:/var/www/html"
    depends_on:
      - db
      - wp

  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${IP}:${PMA_PORT}:80"
    depends_on:
      - db

  db:
    image: "mysql:${MYSQL_TAG}"
    ports:
      - "${IP}:3306:3306"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - "./wp-data:/docker-entrypoint-initdb.d"
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    restart: unless-stopped

volumes:
  db_data:
