################# TenereLabs.com #########################
# Before proceeding copy .env.example into .env file and change variables if needed

version: "3.7"

services:
  wp:
    build: .
    image: TNCwordpress:${WP_TAG}
    ports:
      - ${IP}:${WP_PORT}:80
    volumes:
      - ".:/var/www/html"
      - "./conf.d/conf.ini:/usr/local/etc/php/conf.d/conf.ini"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${WP_TABLE_PREFIX}"

    depends_on:
      - db
    restart: unless-stopped

  pma:
    image: "phpmyadmin/phpmyadmin"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - "${IP}:${PMA_PORT}:80"
    depends_on:
      - db

  db:
    image: "mysql:${MYSQL_TAG}"
    ports:
      - "3306:3306"
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "${DB_NAME}" # Create your database
      MYSQL_USER: "${DB_USER}" # your database user
      MYSQL_PASSWORD: "${DB_PASSWORD}" # your data base password
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}" # Mandatory for the image
    restart: unless-stopped

volumes:
  db_data:
  conf.d:
